INSERT INTO TB_COUNTRY(CONTINENT, NAME, POPULATION) VALUES('EUROPA', 'ALEMANHA', 83020000);
INSERT INTO TB_COUNTRY(CONTINENT, NAME, POPULATION) VALUES('ASIA', 'JAPAO', 126300000);
INSERT INTO TB_COUNTRY(CONTINENT, NAME, POPULATION) VALUES('AMERICA DO NORTE', 'ESTADOS UNIDOS', 331000000);
INSERT INTO TB_COUNTRY(CONTINENT, NAME, POPULATION) VALUES('EUROPA', 'HOLANDA', 17280000);
INSERT INTO TB_COUNTRY(CONTINENT, NAME, POPULATION) VALUES('ASIA', 'COREIA DO SUL', 51710000);

INSERT INTO TB_CARS(BRAND, MODEL, CATEGORY, LAUNCH_YEAR, COUNTRY_ID) VALUES('BMW', 'Serie 3', 'Sedan', 2020, 1);
INSERT INTO TB_CARS(BRAND, MODEL, CATEGORY, LAUNCH_YEAR, COUNTRY_ID) VALUES('Toyota', 'Corolla', 'Sedan', 2021, 2);
INSERT INTO TB_CARS(BRAND, MODEL, CATEGORY, LAUNCH_YEAR, COUNTRY_ID) VALUES('Ford', 'Mustang', 'Esportivo', 2022, 3);
INSERT INTO TB_CARS(BRAND, MODEL, CATEGORY, LAUNCH_YEAR, COUNTRY_ID) VALUES('Volvo', 'XC40', 'SUV', 2023, 4);
INSERT INTO TB_CARS(BRAND, MODEL, CATEGORY, LAUNCH_YEAR, COUNTRY_ID) VALUES('Hyundai', 'Tucson', 'SUV', 2022, 5);